name: release version tag

on:
  push:
    tags: [ "v*.*.*" ]

jobs:
  build:
    permissions:
      contents: read
      checks: write
      attestations: write 
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
        - os: ubuntu-latest
          goos: linux
    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: setup go
      uses: actions/setup-go@v5.3.0
      with:
        go-version: '1.23.2'

    - name: test before release
      run: go test ./...


    - name: build
      run: go build -o bgp_routeinfo-${{ matrix.goos }} -ldflags "-X main.Version=${{ github.sha }}" ./cmd/routeinfo_server

    - name: build statically linked
      run: go build -o bgp_routeinfo-static-${{ matrix.goos }} -ldflags "-X main.Version=${{ github.sha }}"  ./cmd/routeinfo_server
      env:
        CGO_ENABLED: 0

    - name: save statically linked binary
      uses: actions/upload-artifact@v4.6.0
      with:
        name: bgp_routeinfo-${{ matrix.goos }}
        path: ./bgp_routeinfo-*
        overwrite: true


  release:
    permissions:
      attestations: read 
      contents: write
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: setup go
      uses: actions/setup-go@v3
      with:
        go-version: '1.23.2'
    - name: get binaries from previous job
      uses: actions/download-artifact@v4.1.8
    - name: display downloaded files
      run: ls -R
    - name: release with binaries
      uses: softprops/action-gh-release@v1
      with:
        generate_release_notes: true
        prerelease: ${{ endsWith(github.ref, '-alpha') || endsWith(github.ref, '-beta') }}
        files: "bgp_routeinfo-*/bgp_routeinfo-*"
